spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache?serverTimezone=GMT%2B8
    username: root
    password: 18d0b61;9
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.101
    port: 6379

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl


debug: true

